### ISSUE TITLE
Swing mode : only available mode for the unit

### ISSUE THREAD

**Issue by tomitomas** [KaSroka/Toshiba-AC-control#10]
Hi Kamil, 

as you did for merit_a and merit_b features, do you think it's possible to retrieve only the few swing mode available for the unit ? 

right now there are `OFF, SWING_VERTICAL, SWING_HORIZONTAL, SWING_VERTICAL_AND_HORIZONTAL, FIXED_1, FIXED_2, FIXED_3, FIXED_4, FIXED_5`
my unit only allow `OFF, SWING_VERTICAL` :)

**Comment by KaSroka** [comment]
Hi,

Sorry for very late reply. I don't know how it is reported. All we have in this library is from reverse engineering android app - and I haven't found anything about swing capabilities. It may be part of merit features but this part is very cryptic in Toshiba app.

**Comment by KaSroka** [comment]
This should be fixed by #22

**Comment by tomitomas** [comment]
I confirm that now the lib returns : 
`Supported AC swing modes: {None, Off, Swing Vertical} `

👍
