### ISSUE TITLE
MQTT bridge

### ISSUE THREAD

**Issue by holgerpieta** [KaSroka/Toshiba-AC-control#13]
I'm planning to make an Toshiba-AC to MQTT bridge using this library.
In the end it should be a stand-alone program (probably in a container) that needs to be configured with username and password and then regularly send status updates to MQTT and listens for commands from MQTT.
Idea is to use this in node-red for home automation.

Looking at the sample application I start to get a feeling about how I'm going to do that, but I may have question and maybe need some help here and there. The resulting discussions are supposed to go into this issue.
If you think we should discuss somewhere else, please give me a link and close this issue.

Also, in case you already know of such a project, I would be glad for hint, too.

**Comment by KaSroka** [comment]
Hi, nice to hear that this will be used outside of home assistant. If you have any questions just ask them here. If we feel the need for further discussion we can always switch to some other place. This lib is written with async in mind so it should easily connect with async mqtt lib. You can also check [home-assistant-toshiba_ac](https://github.com/h4de5/home-assistant-toshiba_ac) repo.

**Comment by holgerpieta** [comment]
I've been using the bridge for a couple of weeks now and it seems to be working fine, so I guess I'll publish it soon.

The get all the features working I had to rework large parts of the toshiba-ac-control code. I tried to do all changes non-breaking, i.e. without changing the API, but without a home-assistant installation I cannot test this.
I'll submit a pull request in the near future. Then you can test it and see if you like my changes. If they break something, we can then discuss how to fix that.

**Comment by phoenix-anasazi** [comment]
Hi, thank you all for your great work. Is there any progress yet on the MQTT bridge. The python sample code works as expected. I'd like to integrate it into my FHEM installation. This would be ideal via MQTT, otherwise i'd have to run an HA instance for the control of my AC. Thanks again.

**Comment by holgerpieta** [comment]
Ah, right, the bridge is working. Didn't find the time to make it easy to use. Also did not find the time to make a pull request for all the changes I did to the library.
Anyway, here is the bridge with the modified library, including some rudimentary documentation: https://github.com/holgerpieta/Toshiba-AC-mqtt
Use at your own risk.

**Comment by phoenix-anasazi** [comment]
Thanks for your quick response. Unfortunately I couldn't get it to work. Somehow it couldn't decode the merit_fetures and I am not good enough in Python to debug it. I am using a HA instance for now.

**Comment by holgerpieta** [comment]
Ah, that's sad. It works for me, but I cannot say I've tested every and all combinations. And I own only two different devices, so there might be more options than I found.
Anyway, I opened a ticket here: https://github.com/holgerpieta/Toshiba-AC-mqtt/issues/1
If you could try it again and add the output to the issue, I can try to debug it. Most important is the last part just before the crash and including all the exceptions that are printed at the end.

**Comment by holgerpieta** [comment]
@KaSroka: While working on making the library do what I needed, I noticed something you did different to how I did it. It's not wrong or anything, just different, and so I wanted to know why you did it the way you did it.

You code first fetches the energy, then registers the task which will first sleep until the next full 10 minutes, then fetch the energy and then repeat infinitely.
My code directly registers the task which will first fetch the energy, then sleep 10 minutes (no matter the precise minute on the clock), then repeat infinitely.

My reasoning for the change: One has to first call get_devices(), then one can use the returned device list to register the handler for the energy callback. In your code, the first fetching of the energy thereby happens inside of get_devices(), before the callback is registered, so the information is lost. My version defers the first energy fetch until everything is properly setup and the callback handler is registered.
Is there any reason that I missed why you did it that way?

**Comment by KaSroka** [comment]
Yes. the energy is fetched before returning the device list. So when you have the device you can easily check if it reports energy - if it's `None` it will always be none as given device doesn't report the energy. If you have a value - it will update it periodically and you can register to the updates.
