### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by majkelospl** [KaSroka/Toshiba-AC-control#14]
Cześć, nie wiem czy widziałeś moje wcześniejsze wiadomości, twierdziłem, że to ostatnie miejsce gdzie mogę spróbować Cię "złapać". Po pierwsze super, że jesteś Polakiem, większe nadzieje, że się uda :) Do brzegu... mam ten piękny klimatyzator w domu a niestety nie mogę go sterować z pozycji Homekit. Czy jest jakaś szansa abyś ten plugin napisał pod Homebridge? Nie mam pojęcia ile to jest pracy, chętnie coś odpalę gdybyś się zdecydował schylić się nad tematem. Pozdrawiam i życzę dużo sukcesów. Jak nie da rady to też daj znać. Pozdrawiam Michał.

**Comment by KaSroka** [comment]
Hej, niestety nie korzystam z urządzeń apple i nigdy nie miałem z nimi do czynienia. Obawiam się, ze nie mogę pomóc. Jedyny pomysł to home assistant z którym ta biblioteka działa i wykorzystanie go jako mostu między klimatyzacją a homekitem.
