### ISSUE TITLE
Unable to authenticate. JSON response: 'error': 'invalid_grant'

### ISSUE THREAD

**Issue by mill1000** [KaSroka/Toshiba-AC-control#29]
I am unable to authenticate with this tool. I have no problems logging in with the official app.

Here's the Traceback:
```
[2022-05-22 11:47:08,430] DEBUG    toshiba_ac.utils.http_api: Sending POST to https://toshibamobileservice.azurewebsites.net/api/Consumer/Login
[2022-05-22 11:47:09,206] DEBUG    toshiba_ac.utils.http_api: Response code: 200
Traceback (most recent call last):
  File "/home/pi/Toshiba-AC-control/samples/toshiba_ac_gui.py", line 223, in <module>
    app = App(loop, *parse_cred())
  File "/home/pi/Toshiba-AC-control/samples/toshiba_ac_gui.py", line 60, in __init__
    self.loop.run_until_complete(asyncio.gather(self.init()))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/Toshiba-AC-control/samples/toshiba_ac_gui.py", line 154, in init
    await self.device_manager.connect()
  File "/home/pi/Toshiba-AC-control/toshiba_ac/device_manager.py", line 59, in connect
    await self.http_api.connect()
  File "/home/pi/Toshiba-AC-control/toshiba_ac/utils/http_api.py", line 117, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
  File "/home/pi/Toshiba-AC-control/toshiba_ac/utils/http_api.py", line 111, in request_api
    raise err_type(json["Message"])
toshiba_ac.utils.http_api.ToshibaAcHttpApiAuthError: Invalid UserName or Password
```

I dumped the JSON response and got the following:
```
{'ResObj': {'error': 'invalid_grant'}, 'IsSuccess': False, 'Message': 'Invalid UserName or Password', 'StatusCode': 'InvalidUserNameorPassword'}
```

**Comment by jfly** [comment]
Which app did you use @mill1000? I learned from [this HA thread](https://community.home-assistant.io/t/toshiba-home-ac-control/137698/121) that there are actually 2 Toshiba apps:

1. One for North America: [Toshiba AC NA - Apps on Google Play](https://play.google.com/store/apps/details?id=com.midea.toshiba&hl=en_US&gl=US). This app has an email + password login flow.
2. One for the rest of the world: [Toshiba Home AC Control - Apps on Google Play](https://play.google.com/store/apps/details?id=com.toshibatctc.SmartAC&hl=en_US&gl=US). This app has username + password login flow.

I registered my AC unit with the NA app, then discovered the existing of the non-NA app, downloaded it from this sketchy looking website: [Toshiba Home AC Control for Android - APK Download](https://m.apkpure.com/toshiba-home-ac-control/com.toshibatctc.SmartAC), and unfortunately was unable to connect my AC unit to the app, :shrug: 

@KaSroka, I'd love to get this working with North American AC units. Have you or anyone tried to get that going? I'd be happy to give it a shot if you can give any advice about where to start.

**Comment by mill1000** [comment]
I'm using the Toshiba AC NA app. Didn't know about that 2nd app. Interesting.

I _think_ ApkPure is generally pretty legit, but there's always a risk in side loading APKs from unofficial sources.

**Comment by mill1000** [comment]
Interesting thread. Since the Toshiba AC NA app is published by Midea I wonder if one of these alternate projects might be compatible:
https://github.com/mac-zhou/midea-ac-py
or
https://github.com/andersonshatch/midea-ac-py

**Comment by mill1000** [comment]
@jfly I was able to get HA working with my "Toshiba" AC unit that uses the Toshiba AC NA app. 

Use this component: https://github.com/mac-zhou/midea-ac-py

**Comment by mill1000** [comment]
Closing as irrelevant since my "Toshiba" AC unit is actually a Midea unit

**Comment by jfly** [comment]
Thanks for the pointer, @mill1000! I was able to get https://github.com/mac-zhou/midea-ac-py working with my "Toshiba" AC unit as well =)

**Comment by mill1000** [comment]
Hopefully you have more consistent luck than me. I seem to lose connection with the AC unit, but I'll create an issue over there.

**Comment by jfly** [comment]
Ah, bummer. I literally *just* got things set up, so I don't know how reliable the connection is yet.

**Comment by mill1000** [comment]
Another option I've found that works well with my Toshiba unit is [ESPHome Midea](https://esphome.io/components/climate/midea.html) component with a [dongle](https://community.home-assistant.io/t/support-for-midea-a-c/265236)
