### ISSUE TITLE
How to set Outdoor silent mode

### ISSUE THREAD

**Issue by tetienne** [KaSroka/Toshiba-AC-control#30]
Hi,

Looking at [this end user request](https://github.com/h4de5/home-assistant-toshiba_ac/issues/17) for the HA custom component, I’m wondering how I can set the different values for the Outdoor silent mode. 

Apparently, it’s linked to "merit", but to be honest, I don’t understand how they work, knowing there is merit A and B. It’s something directly named by Toshiba?

**Comment by KaSroka** [comment]
Yes, toshiba calls features merit. Each of them (a and b) can be set to one of supported values. For silent mode it is `CDU_SILENT_1` and `CDU_SILENT_2`. All supported modes for given device are accessible in it's `supported` property. i.e. `device.supported.ac_merit_a` will give you a list of all supported "merit a" modes for given device.
