### ISSUE TITLE
Do toshiba api return when the device is in idle mode?

### ISSUE THREAD

**Issue by h4de5** [KaSroka/Toshiba-AC-control#31]
Hello,

I observed something: when I put my AC unit in heat mode and set the target temperature lower to what it is now, I would have expected that the device goes into an "idle" mode - so it remains on, but does not do the heating. same with cooling.

for what I have seen for my device, it continues with the heating/cooling. is this different for your unit? and is it possible to get that state from the API?

best regards

**Comment by KaSroka** [comment]
Hey, what API returns is the desired state so if you set heating it will always return heating. In app it's the same at least for my unit.
