### ISSUE TITLE
Trying to access historical daily energy consumption on a list of AC Devices

### ISSUE THREAD

**Issue by bruadam** [KaSroka/Toshiba-AC-control#45]
Hi, I am trying to get the historical daily energy consumption at a daily (ideally hourly) resolution for energy analysis purposes. 
Do you know a bit more on the documentation of the API for the endpoint: /api/AC/GetGroupACEnergyConsumption?
Or do you have any suggestions how I could get more detailed documentation? 

Best, Bruno

**Comment by Zyxl72** [comment]
hi.. there is no documentation.. everything we know is from reverse enginiering or code checking from apk or with traffic sniffing (MITM)

What i can tell xou from Traffic sniffing.
When you use /api/AC/GetGroupACEnergyConsumption you need to send an JSON along with some Parameter.

{
 "ACDeviceUniqueIdList":[
   "<Your Device ID>"
 ],
 "Timezone":"W. Europe Standard Time",
 "Type":"EnergyDay",
 "FromUtcTime":"2024-01-30T23:00:00.0000000Z",
 "ToUtcTime":"2024-01-31T22:59:59.0000000Z",
 "IsEstia":true,
 "IsSunday":false
}

With his you should be able to get an answer, that again will be JSON with the Time and the Energy used in Watt.

Only thing i noticed that the Consumptioninfo delivered, does not corrolate with the Energyinfo i have from my SmartMeter.
So I'm not sure if you really should trust those values.

**Comment by bruadam** [comment]
Thank you for the explanation. I actually did the same unpacking the APK. 
I found that you can change this "Type" to "EnergyDay", "EnergyYear"  whatsoever as you did. 

I realised that the data are very indicative and have some limitation: negative values were retrieved which is physically not possible. 

Thank you again.
