### ISSUE TITLE
Add support for off-timers

### ISSUE THREAD

**Issue by felixmueller** [KaSroka/Toshiba-AC-control#46]
Hi @KaSroka,
many thanks for maintaining this library! It makes using Toshiba ACs very comfortable via Home Assistant.
I was asking myself if the auto-off-timer-feature, which is usable in the Toshiba App, could be supported by this library to be adapted in the HA plugin in a second step.
You can find my original feature request here: https://github.com/h4de5/home-assistant-toshiba_ac/issues/176
In my understanding (by consulting the Toshiba App), the setter needs to set a value like 0.5, 1.0, 1.5 etc. which is the number of hours the device should be on and the getter needs to read the time the device is turning off (e.g. 11:04).
Thank you very much for looking into this and maybe adding support. It is the very last important feature in my use case, which cannot be controlled without the Toshiba App at the moment.
Best,
Felix

P.S.: Of course, the ACs can be switched off simply using software automation. However, the Toshiba off-timer function is a hardware function, which is displayed as an additional LED on the AC to indicate that a timer is active. Supporting this would also allow multiple users to read and update the timers independently and would always be in sync when using the IR remote.

**Comment by KaSroka** [comment]
I'm not planning to add this functionality, but I'm open to PRs. Here is my old instruction on hot to reverse engineer the android app: https://github.com/h4de5/home-assistant-toshiba_ac/issues/72#issuecomment-1188250565
