### ISSUE TITLE
Issue for consumption and Cdu

### ISSUE THREAD

**Issue by tomitomas** [KaSroka/Toshiba-AC-control#5]
Hello, 

I try to use it locally (on windows) and got few errors

```
toshiba_ac.http_api: Sending GET to https://toshibamobileservice.azurewebsites.net/api/AC/GetCurrentACState 

toshiba_ac.http_api: Response code: 200, JSON: {'ResObj': {'Id': 'xxx', 'ACId': 'xxx', 'ACDeviceUniqueId': 'xxx', 'ACStateData': '31421436316400101e1bfe0b00001002000000', 'OnOff': '31', 'FirmwareVersion': '3.2.01', 'FirmwareUpgradeStatus': '', 'URL': '', 'File': '', 'MeritFeature': '3c00', 'VersionInfo': '00010000', 'FirmwareCode': '0000', 'AdapterType': '0', 'UpdatedDate': '2021-09-06T17:29:17.153Z', 'Lat': 0.0, 'Long': 0.0, 'Model': '2', 'ModeValues': [{'Mode': '41', 'Temp': '15', 'FanSpeed': '36'}, {'Mode': '42', 'Temp': '14', 'FanSpeed': '36'}, {'Mode': '43', 'Temp': '18', 'FanSpeed': '36'}, {'Mode': '44', 'Temp': '16', 'FanSpeed': '41'}, {'Mode': '45', 'Temp': '16', 'FanSpeed': '36'}], 'IsMapped': False, 'FirstConnectionTime': '2020-01-07T22:18:40.098Z', 'LastConnectionTime': '2021-09-06T17:29:17.153Z', 'Cdu': None, 'Fcu': None, 'ConsumerMasterId': 'xxxx', 'PartitionKey': 'xxxx'}, 'IsSuccess': True, 'Message': 'Get Current AC State Successful', 'StatusCode': 'GetCurrentACStateSuccess'}

  File "\toshiba_ac\http_api.py", line 155, in get_device_additional_info
    cdu = res['Cdu']['model_name']
TypeError: 'NoneType' object is not subscriptable
```

to get it working I change line 156 
from `except KeyError:` to `except Exception:`

and then (maybe because of the first error and my change !?)

```
Sending POST to https://toshibamobileservice.azurewebsites.net/api/AC/GetGroupACEnergyConsumption

toshiba_ac.http_api: Response code: 200, JSON: {'ResObj': [{'ACName': None, 'ACDeviceUniqueId': 'xxx', 'EnergyConsumption': None}, {'ACName': None, 'ACDeviceUniqueId': 'xxx', 'EnergyConsumption': None}], 'IsSuccess': True, 'Message': 'Success', 'StatusCode': 'Success'}

  File "toshiba_ac\http_api.py", line 186, in get_devices_energy_consumption
    consumption = sum(int(consumption['Energy']) for consumption in ac['EnergyConsumption'])
TypeError: 'NoneType' object is not iterable
```

**Comment by KaSroka** [comment]
Thanks for reporting this, my AC reports those values so I overlooked this. I will fix this in next version.

**Comment by KaSroka** [comment]
Hi @tomitomas can you check with latest release?

**Comment by tomitomas** [comment]
Hi @KaSroka , 

looks OK with last commits 👍 
thanks ! 

(quick other question : do you think you'll update your first draft in PHP with all solutions you found for Python ? or will Php one be abandoned !?)

**Comment by KaSroka** [comment]
I'm not the author of PHP version. It was created by @h4de5

**Comment by h4de5** [comment]
@tomitomas i have not planed to update that - sorry. i would need an amqp client in php to do so - and even if I had one.. I think once this python package reaches a stable version, there may not be much use for a php version anymore. what is your use case?

**Comment by tomitomas** [comment]
Hi @h4de5 

I've been looking for a similar solution for months ! I even contact the real dev team in toshiba to know if they were thinking about making an open api of their apps. 
My goal : be able to manage my AC from Jeedom domotic platform. Php will be more confortable to do it.

**Comment by h4de5** [comment]
i can think of modifing the sample script a little bit and write a simple wrapper in php using exec calls. but this would probably perform poorly and at best can be used as prototype.

**Comment by tomitomas** [comment]
👍  can be a great start thanks !
