### ISSUE TITLE
Login error?

### ISSUE THREAD

**Issue by felixmueller** [KaSroka/Toshiba-AC-control#52]
The HA integration has stopped working for me a few hours ago. At first I had an error message similar to “Invalid credentials” when performing actions. After restarting the integration I get “DisconnectEvent received while in unexpected state - ConnectionState.DISCONNECTED”.

Can any of you reproduce this? Do you have the same behavior in your fork @laurensk?

**Comment by laurensk** [comment]
Yes I have the same issue. I thought I messed something up in my fork xD.
The funny thing is that this seems to be an issue with the HA integration (https://github.com/h4de5/home-assistant-toshiba_ac) only, this Python library seems to work ok.

**Comment by laurensk** [comment]
Can be closed since this is an issue with the Home Assistant integration only (see https://github.com/h4de5/home-assistant-toshiba_ac/issues/188)
